name: run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dyalog/dyalog

    steps:
      - name: Info
        run: whoami

      - uses: actions/checkout@v2
      
      - uses: docker://dyalog/dyalog:2.12
      - with:
          args: ls

      - name: Run scripts
        run: cd src && ./run.sh
