name: run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dyalog/dyalog

    steps:
      - name: Info
        run: whoami

      - uses: actions/checkout@v2

      - name: Run scripts
        run: cd src && ./run.sh
